doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                server_version: '11.4'
                charset: utf8
                # url: '%env(resolve:DATABASE_URL)%'
                wrapper_class: 'App\Doctrine\Connection'
            admin:
                driver: 'pdo_pgsql'
                server_version: '11.4'
                charset: utf8
                url: '%env(resolve:DATABASE_URL_ADMIN)%'


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: default
                mappings:
                    Fidelity:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Fidelity'
                        prefix: 'App\Entity\Fidelity'
                        alias: Fidelity
                dql:
                    string_functions:
                        unaccent_nl: App\Doctrine\Functions\FnUnaccent
                        cast: Oro\ORM\Query\AST\Functions\Cast
            admin:
                connection: admin
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Admin:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Admin'
                        prefix: 'App\Entity\Admin'
                        alias: Admin
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity/Fidelity'
#                prefix: 'App\Entity\Fidelity'
#                alias: App
