framework:
    ide: 'phpstorm://open?file=%%f&line=%%l'
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        save_path: ~
        enabled: true
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        name: ME_SESSID
        cookie_secure: true
        cookie_samesite: strict
        cookie_lifetime: 86400
        use_cookies: true
        sid_length: 64
    #esi: true
    #fragments: true
    php_errors:
        log: true
